-- Phase 1: auth + member drafts
-- Run in Supabase SQL editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('member', 'maintainer')),
  created_at timestamptz not null default now()
);

create table if not exists public.member_drafts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  slug text not null,
  draft_json jsonb not null,
  updated_at timestamptz not null default now(),
  unique(user_id, slug)
);

alter table public.profiles enable row level security;
alter table public.member_drafts enable row level security;

-- Members can view only their own profile row.
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles
  for select
  using (auth.uid() = id);

-- Members can create/update only their own profile row.
drop policy if exists "profiles_upsert_own" on public.profiles;
create policy "profiles_upsert_own"
  on public.profiles
  for insert
  with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles
  for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- Members can manage only their own drafts when using the anon key.
drop policy if exists "member_drafts_select_own" on public.member_drafts;
create policy "member_drafts_select_own"
  on public.member_drafts
  for select
  using (auth.uid() = user_id);

drop policy if exists "member_drafts_insert_own" on public.member_drafts;
create policy "member_drafts_insert_own"
  on public.member_drafts
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "member_drafts_update_own" on public.member_drafts;
create policy "member_drafts_update_own"
  on public.member_drafts
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "member_drafts_delete_own" on public.member_drafts;
create policy "member_drafts_delete_own"
  on public.member_drafts
  for delete
  using (auth.uid() = user_id);
